CREATE TABLE LIQUOR
(
  ID_LIQUOR                 NUMBER       NOT NULL,
  NAME                      VARCHAR2(20) NOT NULL,
  PRICE                     INT          NOT NULL,
  DATE_OF_EXP               DATE         NOT NULL,
  ID_LIQUOR_TYPE_DICTIONARY NUMBER       NOT NULL,

  CONSTRAINT "LIQUOR_PK" PRIMARY KEY (ID_LIQUOR),
  CONSTRAINT ID_LIQUOR_TYPE_DICTIONARY FOREIGN KEY (ID_LIQUOR_TYPE_DICTIONARY)
  REFERENCES LIQUOR_TYPE_DICTIONARY (ID_LIQUOR_TYPE_DICTIONARY)
);