INSERT INTO LIQUOR (ID_LIQUOR, NAME, PRICE, DATE_OF_EXP, ID_LIQUOR_TYPE_DICTIONARY)
VALUES (1, 'grey goose', 15, '02.07.2022', 1);

INSERT INTO LIQUOR (ID_LIQUOR, NAME, PRICE, DATE_OF_EXP, ID_LIQUOR_TYPE_DICTIONARY)
VALUES (2, 'belvedere', 17, '15.07.2020', 1);

INSERT INTO LIQUOR (ID_LIQUOR, NAME, PRICE, DATE_OF_EXP, ID_LIQUOR_TYPE_DICTIONARY)
VALUES (3, 'stolichnaya', 12, '30.01.2021', 1);

INSERT INTO LIQUOR (ID_LIQUOR, NAME, PRICE, DATE_OF_EXP, ID_LIQUOR_TYPE_DICTIONARY)
VALUES (4, 'bombay sapphire', 14, '01.01.2020',2);

INSERT INTO LIQUOR (ID_LIQUOR, NAME, PRICE, DATE_OF_EXP, ID_LIQUOR_TYPE_DICTIONARY)
VALUES (5, 'hendricks', 16, '19.12.2022', 2);

INSERT INTO LIQUOR (ID_LIQUOR, NAME, PRICE, DATE_OF_EXP, ID_LIQUOR_TYPE_DICTIONARY)
VALUES (6, 'captain morgan', 13, '09.07.2022', 3);

INSERT INTO LIQUOR (ID_LIQUOR, NAME, PRICE, DATE_OF_EXP, ID_LIQUOR_TYPE_DICTIONARY)
VALUES (7, 'kraken', 15, '21.12.2021', 3);

INSERT INTO LIQUOR (ID_LIQUOR, NAME, PRICE, DATE_OF_EXP, ID_LIQUOR_TYPE_DICTIONARY)
VALUES (8, 'kahlua', 14, '01.08.2019', 4);

INSERT INTO LIQUOR (ID_LIQUOR, NAME, PRICE, DATE_OF_EXP, ID_LIQUOR_TYPE_DICTIONARY)
VALUES (9, 'jagermeister', 15, '29.03.2022', 4);

INSERT INTO LIQUOR (ID_LIQUOR, NAME, PRICE, DATE_OF_EXP, ID_LIQUOR_TYPE_DICTIONARY)
VALUES (10, 'don julio blanco', 15, '28.12.2019', 5);

INSERT INTO LIQUOR (ID_LIQUOR, NAME, PRICE, DATE_OF_EXP, ID_LIQUOR_TYPE_DICTIONARY)
VALUES (11, 'patron', 12, '25.12.2023', 5);

INSERT INTO LIQUOR (ID_LIQUOR, NAME, PRICE, DATE_OF_EXP, ID_LIQUOR_TYPE_DICTIONARY)
VALUES (12, 'dry vermouth', 10, '03.03.2020', 6);

INSERT INTO LIQUOR (ID_LIQUOR, NAME, PRICE, DATE_OF_EXP, ID_LIQUOR_TYPE_DICTIONARY)
VALUES (13, 'sw3eet vermouth', 10, '08.10.2021', 6);

INSERT INTO LIQUOR (ID_LIQUOR, NAME, PRICE, DATE_OF_EXP, ID_LIQUOR_TYPE_DICTIONARY)
VALUES (14, 'hennessy vsop', 13, '02.05.2022', 7);

INSERT INTO LIQUOR (ID_LIQUOR, NAME, PRICE, DATE_OF_EXP, ID_LIQUOR_TYPE_DICTIONARY)
VALUES (15, 'courvoisier', 20, '05.09.2020', 7);

INSERT INTO LIQUOR (ID_LIQUOR, NAME, PRICE, DATE_OF_EXP, ID_LIQUOR_TYPE_DICTIONARY)
VALUES (16, 'bulleit', 20, '01.05.2020', 8);

INSERT INTO LIQUOR (ID_LIQUOR, NAME, PRICE, DATE_OF_EXP, ID_LIQUOR_TYPE_DICTIONARY)
VALUES (17, 'knob creek', 20, '09.11.2022', 8);

INSERT INTO LIQUOR (ID_LIQUOR, NAME, PRICE, DATE_OF_EXP, ID_LIQUOR_TYPE_DICTIONARY)
VALUES (18, 'cointreau', 9, '08.10.2021', 6);

COMMIT;
