CREATE TABLE NON_ALC_DRINK
(
  ID_NON_ALC_DRINK           NUMBER       NOT NULL,
  ID_NON_ALC_TYPE_DICTIONARY NUMBER       NOT NULL,
  NAME                       VARCHAR2(20) NOT NULL,
  PRICE                      INT          NOT NULL,
  EXP_DATE                   DATE         NOT NULL,

  CONSTRAINT NON_ALC_DRINK_PK PRIMARY KEY (ID_NON_ALC_DRINK),
  CONSTRAINT NON_ALC_DRINK_FK FOREIGN KEY (ID_NON_ALC_TYPE_DICTIONARY)
  REFERENCES NON_ALC_TYPE_DICTIONARY (ID_NON_ALC_TYPE_DICTIONARY)
);
