INSERT INTO NON_ALC_DRINK (ID_NON_ALC_DRINK, NAME, PRICE, ID_NON_ALC_TYPE_DICTIONARY, EXP_DATE)
VALUES (1, 'orange juice', 7, 1, '07.11.2019');

INSERT INTO NON_ALC_DRINK (ID_NON_ALC_DRINK, NAME, PRICE, ID_NON_ALC_TYPE_DICTIONARY, EXP_DATE)
VALUES (2, 'apple juice', 7, 1, '30.11.2020');

INSERT INTO NON_ALC_DRINK (ID_NON_ALC_DRINK, NAME, PRICE, ID_NON_ALC_TYPE_DICTIONARY, EXP_DATE)
VALUES (3, 'pineapple juice', 7, 1, '11.11.2020');

INSERT INTO NON_ALC_DRINK (ID_NON_ALC_DRINK, NAME, PRICE, ID_NON_ALC_TYPE_DICTIONARY, EXP_DATE)
VALUES (4, 'tomato juice', 7, 1, '19.08.2019');

INSERT INTO NON_ALC_DRINK (ID_NON_ALC_DRINK, NAME, PRICE, ID_NON_ALC_TYPE_DICTIONARY, EXP_DATE)
VALUES (5, 'lemonade', 8, 1, '08.03.2020');

INSERT INTO NON_ALC_DRINK (ID_NON_ALC_DRINK, NAME, PRICE, ID_NON_ALC_TYPE_DICTIONARY, EXP_DATE)
VALUES (6, 'coca-cola', 6, 2, '20.12.2019');

INSERT INTO NON_ALC_DRINK (ID_NON_ALC_DRINK, NAME, PRICE, ID_NON_ALC_TYPE_DICTIONARY, EXP_DATE)
VALUES (7, 'sprite', 6, 2, '02.03.2021');

INSERT INTO NON_ALC_DRINK (ID_NON_ALC_DRINK, NAME, PRICE, ID_NON_ALC_TYPE_DICTIONARY, EXP_DATE)
VALUES (8, 'carbonated water', 6, 2, '30.11.2019');

INSERT INTO NON_ALC_DRINK (ID_NON_ALC_DRINK, NAME, PRICE, ID_NON_ALC_TYPE_DICTIONARY, EXP_DATE)
VALUES (9, 'tonic', 6, 2, '02.03.2020');

INSERT INTO NON_ALC_DRINK (ID_NON_ALC_DRINK, NAME, PRICE, ID_NON_ALC_TYPE_DICTIONARY, EXP_DATE)
VALUES (10, 'ginger beer', 6, 2, '12.07.2019');

INSERT INTO NON_ALC_DRINK (ID_NON_ALC_DRINK, NAME, PRICE, ID_NON_ALC_TYPE_DICTIONARY, EXP_DATE)
VALUES (11, 'milk', 6, 1, '07.05.2020');

INSERT INTO NON_ALC_DRINK (ID_NON_ALC_DRINK, NAME, PRICE, ID_NON_ALC_TYPE_DICTIONARY, EXP_DATE)
VALUES (12, 'espresso', 10, 3, '29.12.2019');

INSERT INTO NON_ALC_DRINK (ID_NON_ALC_DRINK, NAME, PRICE, ID_NON_ALC_TYPE_DICTIONARY, EXP_DATE)
VALUES (13, 'cappuccino', 13, 3, '15.09.2019');

INSERT INTO NON_ALC_DRINK (ID_NON_ALC_DRINK, NAME, PRICE, ID_NON_ALC_TYPE_DICTIONARY, EXP_DATE)
VALUES (14, 'americano', 12, 3, '14.12.2020');

INSERT INTO NON_ALC_DRINK (ID_NON_ALC_DRINK, NAME, PRICE, ID_NON_ALC_TYPE_DICTIONARY, EXP_DATE)
VALUES (15, 'black tea', 9, 4, '27.06.2019');

INSERT INTO NON_ALC_DRINK (ID_NON_ALC_DRINK, NAME, PRICE, ID_NON_ALC_TYPE_DICTIONARY, EXP_DATE)
VALUES (16, 'green tea', 9, 4, '22.06.2019');

INSERT INTO NON_ALC_DRINK (ID_NON_ALC_DRINK, NAME, PRICE, ID_NON_ALC_TYPE_DICTIONARY, EXP_DATE)
VALUES (17, 'grenadine', 9, 5, '25.11.2020');

INSERT INTO NON_ALC_DRINK (ID_NON_ALC_DRINK, NAME, PRICE, ID_NON_ALC_TYPE_DICTIONARY, EXP_DATE)
VALUES (18, 'sour mix', 6, 2, '21.10.2022');

COMMIT;
