INSERT INTO COCKTAIL (ID_COCKTAIL, NAME, PRICE)
VALUES (1, 'manhattan', 20);

INSERT INTO COCKTAIL (ID_COCKTAIL, NAME, PRICE)
VALUES (2, 'long island ice tea', 23);

INSERT INTO COCKTAIL (ID_COCKTAIL, NAME, PRICE)
VALUES (3, 'espresso martini', 20);

INSERT INTO COCKTAIL (ID_COCKTAIL, NAME, PRICE)
VALUES (4, 'whiskey sour', 18);

INSERT INTO COCKTAIL (ID_COCKTAIL, NAME, PRICE)
VALUES (5, 'moscow mule', 18);

INSERT INTO COCKTAIL (ID_COCKTAIL, NAME, PRICE)
VALUES (6, 'bloody mary', 21);

INSERT INTO COCKTAIL (ID_COCKTAIL, NAME, PRICE)
VALUES (7, 'dry vodka martini', 22);

INSERT INTO COCKTAIL (ID_COCKTAIL, NAME, PRICE)
VALUES (8, 'dirty vodka martini', 22);

INSERT INTO COCKTAIL (ID_COCKTAIL, NAME, PRICE)
VALUES (9, 'dry gin martini', 24);

INSERT INTO COCKTAIL (ID_COCKTAIL, NAME, PRICE)
VALUES (10, 'paloma', 18);

COMMIT ;