CREATE TABLE LIQUOR_FOR_COCKTAIL
(
  ID_LIQUOR_FOR_COCKTAIL NUMBER NOT NULL,
  ID_COCKTAIL            NUMBER NOT NULL,
  ID_LIQUOR              NUMBER NOT NULL,

  CONSTRAINT LIQUOR_FOR_COCKTAIL_PK PRIMARY KEY (ID_LIQUOR_FOR_COCKTAIL),
  CONSTRAINT LIQUOR_FOR_COCKTAIL_COCKT_FK FOREIGN KEY (ID_COCKTAIL)
  REFERENCES COCKTAIL (ID_COCKTAIL),
  CONSTRAINT LIQUOR_FOR_COCKTAIL_LIQ_FK FOREIGN KEY (ID_LIQUOR)
  REFERENCES LIQUOR (ID_LIQUOR)
);