INSERT INTO LIQUOR_FOR_COCKTAIL (ID_LIQUOR_FOR_COCKTAIL, ID_COCKTAIL, ID_LIQUOR)
VALUES (1, 1, 6);

INSERT INTO LIQUOR_FOR_COCKTAIL (ID_LIQUOR_FOR_COCKTAIL, ID_COCKTAIL, ID_LIQUOR)
VALUES (2, 1, 16);

INSERT INTO LIQUOR_FOR_COCKTAIL (ID_LIQUOR_FOR_COCKTAIL, ID_COCKTAIL, ID_LIQUOR)
VALUES (3, 2, 3);

INSERT INTO LIQUOR_FOR_COCKTAIL (ID_LIQUOR_FOR_COCKTAIL, ID_COCKTAIL, ID_LIQUOR)
VALUES (4, 2, 4);

INSERT INTO LIQUOR_FOR_COCKTAIL (ID_LIQUOR_FOR_COCKTAIL, ID_COCKTAIL, ID_LIQUOR)
VALUES (5, 2, 13);

INSERT INTO LIQUOR_FOR_COCKTAIL (ID_LIQUOR_FOR_COCKTAIL, ID_COCKTAIL, ID_LIQUOR)
VALUES (6, 2, 11);

INSERT INTO LIQUOR_FOR_COCKTAIL (ID_LIQUOR_FOR_COCKTAIL, ID_COCKTAIL, ID_LIQUOR)
VALUES (7, 2, 18);

INSERT INTO LIQUOR_FOR_COCKTAIL (ID_LIQUOR_FOR_COCKTAIL, ID_COCKTAIL, ID_LIQUOR)
VALUES (8, 3, 1);

INSERT INTO LIQUOR_FOR_COCKTAIL (ID_LIQUOR_FOR_COCKTAIL, ID_COCKTAIL, ID_LIQUOR)
VALUES (9, 4, 17);

INSERT INTO LIQUOR_FOR_COCKTAIL (ID_LIQUOR_FOR_COCKTAIL, ID_COCKTAIL, ID_LIQUOR)
VALUES (10, 5, 3);

INSERT INTO LIQUOR_FOR_COCKTAIL (ID_LIQUOR_FOR_COCKTAIL, ID_COCKTAIL, ID_LIQUOR)
VALUES (11, 6, 2);

INSERT INTO LIQUOR_FOR_COCKTAIL (ID_LIQUOR_FOR_COCKTAIL, ID_COCKTAIL, ID_LIQUOR)
VALUES (12, 7, 12);

INSERT INTO LIQUOR_FOR_COCKTAIL (ID_LIQUOR_FOR_COCKTAIL, ID_COCKTAIL, ID_LIQUOR)
VALUES (13, 7, 3);

INSERT INTO LIQUOR_FOR_COCKTAIL (ID_LIQUOR_FOR_COCKTAIL, ID_COCKTAIL, ID_LIQUOR)
VALUES (14, 8, 1);

INSERT INTO LIQUOR_FOR_COCKTAIL (ID_LIQUOR_FOR_COCKTAIL, ID_COCKTAIL, ID_LIQUOR)
VALUES (15, 9, 5);

INSERT INTO LIQUOR_FOR_COCKTAIL (ID_LIQUOR_FOR_COCKTAIL, ID_COCKTAIL, ID_LIQUOR)
VALUES (16, 9, 12);

INSERT INTO LIQUOR_FOR_COCKTAIL (ID_LIQUOR_FOR_COCKTAIL, ID_COCKTAIL, ID_LIQUOR)
VALUES (17, 10, 10);


COMMIT;