INSERT INTO NON_ALC_FOR_COCKTAIL (ID_NON_ALC_FOR_COCKTAIL, ID_COCKTAIL, ID_NON_ALC_DRINK)
VALUES (1, 2, 6);

INSERT INTO NON_ALC_FOR_COCKTAIL (ID_NON_ALC_FOR_COCKTAIL, ID_COCKTAIL, ID_NON_ALC_DRINK)
VALUES (2, 2, 6);

INSERT INTO NON_ALC_FOR_COCKTAIL (ID_NON_ALC_FOR_COCKTAIL, ID_COCKTAIL, ID_NON_ALC_DRINK)
VALUES (3, 3, 12);

INSERT INTO NON_ALC_FOR_COCKTAIL (ID_NON_ALC_FOR_COCKTAIL, ID_COCKTAIL, ID_NON_ALC_DRINK)
VALUES (4, 4, 18);

INSERT INTO NON_ALC_FOR_COCKTAIL (ID_NON_ALC_FOR_COCKTAIL, ID_COCKTAIL, ID_NON_ALC_DRINK)
VALUES (5, 5, 10);

INSERT INTO NON_ALC_FOR_COCKTAIL (ID_NON_ALC_FOR_COCKTAIL, ID_COCKTAIL, ID_NON_ALC_DRINK)
VALUES (6, 6, 4);

INSERT INTO NON_ALC_FOR_COCKTAIL (ID_NON_ALC_FOR_COCKTAIL, ID_COCKTAIL, ID_NON_ALC_DRINK)
VALUES (7, 10, 17);

INSERT INTO NON_ALC_FOR_COCKTAIL (ID_NON_ALC_FOR_COCKTAIL, ID_COCKTAIL, ID_NON_ALC_DRINK)
VALUES (8, 10, 7);

COMMIT ;