INSERT INTO COCKTAIL_FOR_MENU (ID_COCKTAIL_FOR_MENU, ID_COCKTAIL, ID_BEVERAGE_MENU)
VALUES (1, 1, 1);

INSERT INTO COCKTAIL_FOR_MENU (ID_COCKTAIL_FOR_MENU, ID_COCKTAIL, ID_BEVERAGE_MENU)
VALUES (2, 2, 1);

INSERT INTO COCKTAIL_FOR_MENU (ID_COCKTAIL_FOR_MENU, ID_COCKTAIL, ID_BEVERAGE_MENU)
VALUES (3, 3, 1);

INSERT INTO COCKTAIL_FOR_MENU (ID_COCKTAIL_FOR_MENU, ID_COCKTAIL, ID_BEVERAGE_MENU)
VALUES (4, 10, 1);

INSERT INTO COCKTAIL_FOR_MENU (ID_COCKTAIL_FOR_MENU, ID_COCKTAIL, ID_BEVERAGE_MENU)
VALUES (5, 9, 1);

INSERT INTO COCKTAIL_FOR_MENU (ID_COCKTAIL_FOR_MENU, ID_COCKTAIL, ID_BEVERAGE_MENU)
VALUES (6, 8, 1);

INSERT INTO COCKTAIL_FOR_MENU (ID_COCKTAIL_FOR_MENU, ID_COCKTAIL, ID_BEVERAGE_MENU)
VALUES (7, 6, 2);

COMMIT;