INSERT INTO LIQUOR_FOR_MENU (ID_LIQUOR_FOR_MENU, ID_LIQUOR, ID_BEVERAGE_MENU)
VALUES (1, 2, 1);

INSERT INTO LIQUOR_FOR_MENU (ID_LIQUOR_FOR_MENU, ID_LIQUOR, ID_BEVERAGE_MENU)
VALUES (2, 5, 1);

INSERT INTO LIQUOR_FOR_MENU (ID_LIQUOR_FOR_MENU, ID_LIQUOR, ID_BEVERAGE_MENU)
VALUES (3, 7, 1);

INSERT INTO LIQUOR_FOR_MENU (ID_LIQUOR_FOR_MENU, ID_LIQUOR, ID_BEVERAGE_MENU)
VALUES (4, 9, 1);

INSERT INTO LIQUOR_FOR_MENU (ID_LIQUOR_FOR_MENU, ID_LIQUOR, ID_BEVERAGE_MENU)
VALUES (5, 10, 1);

INSERT INTO LIQUOR_FOR_MENU (ID_LIQUOR_FOR_MENU, ID_LIQUOR, ID_BEVERAGE_MENU)
VALUES (6, 14, 1);

INSERT INTO LIQUOR_FOR_MENU (ID_LIQUOR_FOR_MENU, ID_LIQUOR, ID_BEVERAGE_MENU)
VALUES (7, 15, 1);

INSERT INTO LIQUOR_FOR_MENU (ID_LIQUOR_FOR_MENU, ID_LIQUOR, ID_BEVERAGE_MENU)
VALUES (8, 16, 1);

COMMIT;