CREATE TABLE NON_ALC_FOR_MENU
(
  ID_NON_ALC_FOR_MENU NUMBER NOT NULL,
  ID_NON_ALC_DRINK    NUMBER NOT NULL,
  ID_BEVERAGE_MENU    NUMBER NOT NULL,

  CONSTRAINT NON_ALC_FOR_MENU_PK PRIMARY KEY (ID_NON_ALC_FOR_MENU),
  CONSTRAINT NON_ALC_FOR_MENU_NON_ALC_FK FOREIGN KEY (ID_NON_ALC_DRINK)
  REFERENCES NON_ALC_DRINK (ID_NON_ALC_DRINK),
  CONSTRAINT NON_ALC_FOR_MENU_BEV_MENU_FK FOREIGN KEY (ID_BEVERAGE_MENU)
  REFERENCES BEVERAGE_MENU (ID_BEVERAGE_MENU)
);