INSERT INTO NON_ALC_FOR_MENU (ID_NON_ALC_FOR_MENU, ID_NON_ALC_DRINK, ID_BEVERAGE_MENU)
VALUES (1, 1, 1);

INSERT INTO NON_ALC_FOR_MENU (ID_NON_ALC_FOR_MENU, ID_NON_ALC_DRINK, ID_BEVERAGE_MENU)
VALUES (2, 2, 1);

INSERT INTO NON_ALC_FOR_MENU (ID_NON_ALC_FOR_MENU, ID_NON_ALC_DRINK, ID_BEVERAGE_MENU)
VALUES (3, 3, 1);

INSERT INTO NON_ALC_FOR_MENU (ID_NON_ALC_FOR_MENU, ID_NON_ALC_DRINK, ID_BEVERAGE_MENU)
VALUES (4, 5, 1);

INSERT INTO NON_ALC_FOR_MENU (ID_NON_ALC_FOR_MENU, ID_NON_ALC_DRINK, ID_BEVERAGE_MENU)
VALUES (5, 6, 1);

INSERT INTO NON_ALC_FOR_MENU (ID_NON_ALC_FOR_MENU, ID_NON_ALC_DRINK, ID_BEVERAGE_MENU)
VALUES (6, 7, 1);

INSERT INTO NON_ALC_FOR_MENU (ID_NON_ALC_FOR_MENU, ID_NON_ALC_DRINK, ID_BEVERAGE_MENU)
VALUES (7, 8, 1);

INSERT INTO NON_ALC_FOR_MENU (ID_NON_ALC_FOR_MENU, ID_NON_ALC_DRINK, ID_BEVERAGE_MENU)
VALUES (8, 1, 2);

INSERT INTO NON_ALC_FOR_MENU (ID_NON_ALC_FOR_MENU, ID_NON_ALC_DRINK, ID_BEVERAGE_MENU)
VALUES (9, 5, 2);

INSERT INTO NON_ALC_FOR_MENU (ID_NON_ALC_FOR_MENU, ID_NON_ALC_DRINK, ID_BEVERAGE_MENU)
VALUES (10, 12, 2);

INSERT INTO NON_ALC_FOR_MENU (ID_NON_ALC_FOR_MENU, ID_NON_ALC_DRINK, ID_BEVERAGE_MENU)
VALUES (11, 13, 2);

INSERT INTO NON_ALC_FOR_MENU (ID_NON_ALC_FOR_MENU, ID_NON_ALC_DRINK, ID_BEVERAGE_MENU)
VALUES (12, 14, 1);

INSERT INTO NON_ALC_FOR_MENU (ID_NON_ALC_FOR_MENU, ID_NON_ALC_DRINK, ID_BEVERAGE_MENU)
VALUES (13, 15, 2);

INSERT INTO NON_ALC_FOR_MENU (ID_NON_ALC_FOR_MENU, ID_NON_ALC_DRINK, ID_BEVERAGE_MENU)
VALUES (14, 16, 2);

COMMIT;

